server:
  port: 80


spring:
  application:
    name: consul-consumer-order
    #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 9500
      discovery:
        service-name: ${spring.application.name}
