server:
  port: 8006


spring:
  application:
    name: consul-provider-payment
    #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 9500
      discovery:
        service-name: ${spring.application.name}